
###
POST http://localhost:9099/api/department
Content-Type: application/json

{
    "departmentCode":"D3",
    "departmentName":"EEE"
}

###
GET http://localhost:9099/api/department/id/60ac7283ff70725b83c8dab2
Accept: application/json

###
PUT http://localhost:9099/api/department/id/60add24614fc127b728417a2
Content-Type: application/json

{
  "departmentCode":"D1",
  "departmentName":"Computer Science 2"
}


###
GET http://localhost:9099/api/departments
Accept: application/json


###
DELETE http://localhost:9099/api/department/id/60acbac5d2318f1cd45bf143
Accept: application/json
